server:
  port: 8090
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/users?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  application:
    name: auth_server
logging:
  level:
    root: INFO
  path:
    file: auth_server.log